
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sheetcast

Transform:
- AWS::Serverless-2016-10-31


Resources:
  RegenerateFeed:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that returns a static string.
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 120
      Environment:
        Variables:
          GOOGLE_API_CLIENT_EMAIL: !Ref GOOGLE_API_CLIENT_EMAIL
          GOOGLE_API_PRIVATE_KEY: !Ref GOOGLE_API_PRIVATE_KEY
          S3_BUCKET_NAME: !Ref S3_BUCKET_NAME
          AWS_S3_REGION: !Ref AWS_S3_REGION
          SLACK_WEBHOOK_URL: !Ref SLACK_WEBHOOK_URL
          RUN_LOCAL: !Ref RUN_LOCAL
      Policies:
        - AWSLambdaBasicExecutionRole
    
